services:

  pm1:
    image: mariadb/columnstore
    shm_size: '512mb'
    hostname: mcs1
    container_name: mcs1
    environment:
      - CLUSTER=false
      - PM1=mcs1
    volumes:
      - ./assets/data/:/tmp/data/
    ports:
      - 3307:3306
